#!usr/bin/env bash

# Function to display information about a specific subdomain
function display_subdomain_info() {
    local domain="$1"
    local subdomain="$2"
    
    local record_type=$(nslookup -type=ANY "$subdomain.$domain" | awk '/^'"$subdomain.$domain"'/{getline; print $1}')
    local destination=$(nslookup "$subdomain.$domain" | awk '/^Address: /{print $2}')
    
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Check if domain and subdomain parameters are provided
if [[ -n "$1" && -n "$2" ]]; then
    display_subdomain_info "$1" "$2"
else
    # Display information for default subdomains: www, lb-01, web-01, web-02
    display_subdomain_info "$1" "www"
    display_subdomain_info "$1" "lb-01"
    display_subdomain_info "$1" "web-01"
    display_subdomain_info "$1" "web-02"
fi

