#!/usr/bin/env bash
# Bash script that install nginx on your web-01 server
sudo apt update
sudo apt install nginx -y
# Firewall- port 80
sudo ufw allow 'Nginx HTTP'
# Index file and start
echo "Hello World!" > /var/www/index.html
sudo service nginx start
# make the redirection
sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
# 404 file
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404_page.html
# make the redirection to 404
sed -i "/listen 80 default_server/a error_page 404 /custom_404_page.html; location = /custom_404_page.html {root /usr/share/nginx/html;\n internal;}" /etc/nginx/sites-available/default
# restart nginx server
sudo service nginx restart
