#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script

sudo apt update -y
sudo apt -y install haproxy

#change permission to allow us to easily create files in this directory
sudo chmod 777 /etc/default/haproxy /etc/haproxy/haproxy.cfg

sudo echo "ENABLED=1" >> /etc/default/haproxy

sudo echo "
frontend front_server
    bind *:80
    default_backend back_server

backend back_server
    balance roundrobin
    server web-01 100.25.117.48:80 check
    server web-02 54.146.58.123:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
