#!/usr/bin/env bash

# On the 9th iteration, display "Best School" then "Hi"  in new line

count=0

while [ $count -lt 10]
do
	echo "Best School"
	if [ $count -eq 9 ]
	then
		echo "Hi"
	fi
	(( count++ ))
done
