#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.
cp /etc/hosts ~/hosts.new
sed -1 s/127.0.0.1/127.0.0.2/ ~hosts.new
echo "8.8.8.8 facebook.com" >> ~hosts.ew
cp -f ~/hosts.new /etc/hosts
